import os
import glob

BUILD_SCRIPTS = [
    "scripts/build_index.py",
    "scripts/build_missav.py",
    "scripts/build_onejav.py",
    "scripts/build_javct.py",
    "scripts/build_models.py",
    "scripts/build_codes.py",
    "scripts/build_sitemap.py",
]

THEME_CSS = """
[data-theme="light"] {
  --bg:#f8fafc;
  --surface:#ffffff;
  --card:#ffffff;
  --card-hover:#f1f5f9;
  --border:#e2e8f0;
  --text:#0f172a;
  --text-dim:#64748b;
  --line:rgba(0,0,0,0.1);
  --pill:#e2e8f0;
  --pill-hover:#cbd5e1;
}
* { box-sizing: border-box; }
"""

THEME_JS = """
<script>
  (function(){
    const toggle = document.createElement('button');
    toggle.innerHTML = '🌓';
    toggle.title = 'Toggle Theme';
    toggle.style.cssText = 'position:fixed;bottom:20px;right:20px;z-index:9999;background:var(--card, #fff);border:1px solid var(--border, #ccc);color:var(--text, #000);padding:10px;border-radius:50%;cursor:pointer;box-shadow:0 4px 12px rgba(0,0,0,0.2);display:flex;align-items:center;justify-content:center;font-size:22px;';
    toggle.onclick = () => {
      const isLight = document.body.getAttribute('data-theme') === 'light';
      document.body.setAttribute('data-theme', isLight ? 'dark' : 'light');
      localStorage.setItem('theme', isLight ? 'dark' : 'light');
    };
    document.body.appendChild(toggle);
    if(localStorage.getItem('theme') === 'light') document.body.setAttribute('data-theme', 'light');
  })();
</script>
</body>
"""

for pyfile in BUILD_SCRIPTS:
    with open(pyfile, "r", encoding="utf-8") as f:
        content = f.read()

    # Inject CSS
    if '[data-theme="light"]' not in content:
        content = content.replace("* { box-sizing: border-box; }", THEME_CSS)
        content = content.replace("*{ box-sizing:border-box; margin:0; padding:0; }", THEME_CSS + "\n* { margin:0; padding:0; }")

    # Inject JS
    if 'localStorage.getItem(\'theme\')' not in content:
        content = content.replace("</body>", THEME_JS)

    with open(pyfile, "w", encoding="utf-8") as f:
        f.write(content)
        print(f"Patched {pyfile}")

# Special patch for docs/index.html (since it's static, not generated by a script except manually)
with open("docs/index.html", "r", encoding="utf-8") as f:
    idx = f.read()
if '[data-theme="light"]' not in idx:
    idx = idx.replace("* { box-sizing: border-box; }", THEME_CSS)
if 'localStorage.getItem(\'theme\')' not in idx:
    idx = idx.replace("</body>", THEME_JS)
with open("docs/index.html", "w", encoding="utf-8") as f:
    f.write(idx)
print("Patched docs/index.html")

